# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "timeline_fu"
  s.version = "0.4.1.trabian1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Golick", "Mathieu Martin", "Francois Beausoleil"]
  s.date = "2013-03-06"
  s.description = "Easily build timelines, much like GitHub's news feed"
  s.email = "james@giraffesoft.ca"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "generators/timeline_fu/USAGE",
    "generators/timeline_fu/templates/migration.rb",
    "generators/timeline_fu/templates/model.rb",
    "generators/timeline_fu/timeline_fu_generator.rb",
    "init.rb",
    "lib/generators/timeline_fu/USAGE",
    "lib/generators/timeline_fu/timeline_fu_generator.rb",
    "lib/timeline_fu.rb",
    "lib/timeline_fu/fires.rb",
    "lib/timeline_fu/macros.rb",
    "lib/timeline_fu/matchers.rb",
    "shoulda_macros/timeline_fu_shoulda.rb",
    "test/fires_test.rb",
    "test/test_helper.rb",
    "timeline_fu.gemspec"
  ]
  s.homepage = "http://github.com/giraffesoft/timeline_fu"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Easily build timelines, much like GitHub's news feed"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

